import re
from typing import List, Optional
from backend.app.core.config import settings
from backend.app.core.logging import logger
from backend.app.schemas.evidence import Evidence


def sanitize_and_validate_llm_output(summary: str, evidence_list: List[Evidence]) -> bool:
    """
    Guardrail: Checks that any numeric figures generated by the LLM
    actually existed in the input evidence, preventing hallucinations.
    """
    numbers_in_summary = re.findall(r"\b\d+(?:[.,]\d+)?\b", summary)
    allowed_numbers = set()

    for ev in evidence_list:
        allowed_numbers.add(str(round(ev.calibrated_score * 100)))
        allowed_numbers.add(str(round(ev.raw_score * 100)))
        for v in ev.details.values():
            if isinstance(v, (int, float)):
                allowed_numbers.add(str(v))
                allowed_numbers.add(str(int(v)))
            elif isinstance(v, str):
                for match in re.findall(r"\b\d+(?:[.,]\d+)?\b", v):
                    allowed_numbers.add(match)

    for num in numbers_in_summary:
        # Ignore common safe integers like 1, 2, 3 in sentences
        if num in {"1", "2", "3"}:
            continue
        if num not in allowed_numbers and num.replace(",", "") not in allowed_numbers:
            logger.warning("LLM hallucinated number %s not present in evidence. Discarding output.", num)
            return False

    return True


async def generate_llm_summary(
    band: str,
    overall_risk: float,
    confidence: str,
    top_evidence: List[Evidence],
) -> Optional[str]:
    """
    Optionally rewrites the structured evidence into a fluent plain-English
    investigator summary with strict hallucination checks and timeout.
    """
    if not settings.LLM_ENABLED or not settings.LLM_API_KEY:
        return None

    # Construct facts prompt
    facts = []
    for e in top_evidence:
        facts.append(f"- [{e.severity.upper()}] {e.title}: {e.reason}")

    prompt = (
        f"You are ClaimGuard AI, an investigator assistant. Summarize these fraud signals:\n"
        f"Verdict: {band} Fraud Risk ({round(overall_risk * 100)}%). Confidence: {confidence}.\n"
        f"Evidence facts:\n" + "\n".join(facts) + "\n\n"
        f"Instructions: Write exactly 2-3 concise sentences for an insurance fraud claims examiner. "
        f"State the risk verdict and key findings. Do NOT invent new facts or numbers. "
        f"If confidence is '{confidence}' and not high, note that input quality was limited."
    )

    try:
        import httpx
        # Support OpenAI / Gemini / Anthropic via direct HTTP or compatible API
        headers = {"Authorization": f"Bearer {settings.LLM_API_KEY}", "Content-Type": "application/json"}
        payload = {
            "model": "gpt-4o-mini",
            "messages": [
                {"role": "system", "content": "You write concise, fact-checked claims investigator summaries."},
                {"role": "user", "content": prompt},
            ],
            "max_tokens": 150,
            "temperature": 0.2,
        }

        async with httpx.AsyncClient(timeout=4.0) as client:
            resp = await client.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload)
            if resp.status_code == 200:
                data = resp.json()
                summary = data["choices"][0]["message"]["content"].strip()
                if sanitize_and_validate_llm_output(summary, top_evidence):
                    return summary
    except Exception as e:
        logger.info("LLM summary generation skipped or failed (%s). Using template summary.", e)

    return None
