from typing import Any, Dict


TEMPLATES = {
    # Image
    "IMG-C2PA-01": "Content credentials cryptographically certify this image was generated by AI.",
    "IMG-C2PA-02": "Cryptographic content credentials confirm original capture provenance.",
    "IMG-AI-01": "The image exhibits visual and frequency artifacts characteristic of AI synthesis ({p:.0%} likelihood).",
    "IMG-ELA-01": "Localized compression inconsistency detected via Error Level Analysis (suspected splice or copy-move).",
    "IMG-NOISE-01": "High-frequency noise residual variance is inconsistent across image blocks.",
    "IMG-EXIF-01": "Standard camera EXIF metadata is absent (frequently stripped by social messaging apps).",
    "IMG-EXIF-02a": "Image metadata explicitly specifies an AI generation tool: {software}.",
    "IMG-EXIF-02b": "Image metadata indicates post-capture editing software: {software}.",
    "IMG-EXIF-03": "Camera capture timestamp post-dates file modification time ({capture} vs {modify}).",
    "IMG-DUP-01": "This photo is a duplicate or near-duplicate of claim {other_id} ({sim:.0%} match).",

    # Document
    "DOC-META-01": "PDF metadata indicates creation with an online consumer editing tool ({producer}).",
    "DOC-META-02": "PDF was modified significantly after its initial generation (created {created}, modified {modified}).",
    "DOC-META-03": "PDF structure contains multiple appended revision updates (%%EOF increments).",
    "DOC-META-04": "Document creation timestamp is inconsistent with document date or claim date.",
    "DOC-FONT-01": "Font mismatch detected: '{field}' uses font '{font_a}' differing from surrounding column '{font_b}'.",
    "DOC-FONT-02": "Inconsistent font sizing or vertical baseline offset detected in line: '{text}'.",
    "DOC-OVERLAY-01": "Visible rasterized text differs from the underlying selectable digital text layer.",
    "DOC-OCR-01": "Abnormally low OCR confidence detected in critical numeric field '{field}'.",
    "DOC-LOGIC-01": "Line items sum to {expected:,.2f} {currency}, but the stated invoice total is {found:,.2f} {currency}.",
    "DOC-LOGIC-02": "Tax or subtotal calculation does not match stated values (expected {expected:,.2f}, found {found:,.2f}).",
    "DOC-LOGIC-03": "Invalid date chronology: {reason}.",
    "DOC-LOGIC-04": "Identification / policy number '{value}' failed checksum or format validation.",
    "DOC-LOGIC-05": "Field '{field}' differs across document pages ('{val1}' vs '{val2}').",
    "DOC-LOGIC-06": "Inconsistent numeric formatting (mixed thousand separators or decimal notations).",
    "DOC-LOGIC-07": "Amount written in words ('{words}') contradicts numeric amount ({digits:,.2f}).",
    "DOC-CNN-01": "Document tamper detector localized an anomalous patch around field '{field}' ({score:.0%} confidence).",
    "DOC-ANOM-01": "Word-level layout anomaly detected: '{word}' deviates significantly from page typographic distribution.",
    "DOC-VIS-01": "Visual compression discontinuity detected over textual region on scanned page.",

    # Identity
    "ID-FACE-01": "Facial biometrics do not match between ID photo and submitted selfie (similarity {sim:.2f}).",
    "ID-FACE-02": "Ambiguous biometric match (similarity {sim:.2f}); potential photo morphing or severe lighting degradation.",
    "ID-DEEP-01": "Submitted selfie exhibits synthetic deepfake face artifacts ({p:.0%} AI probability).",

    # Claim Cross-Checks
    "CLM-X-01": "Photo capture date ({photo_date}) is outside the claimed incident window ({incident_date}).",
    "CLM-X-02": "Document total amount ({doc_total:,.2f} {currency}) does not match the claimed amount ({claim_total:,.2f} {currency}).",
    "CLM-X-03": "Claimant name '{claimant_name}' differs from document party name '{doc_name}'.",
    "CLM-X-04": "Photo has been reused across claims (matches claim ID {other_id}).",
    "CLM-X-05": "Document creation timestamp ({doc_date}) is later than the insurance claim filing date ({claim_date}).",
}


def render_evidence_reason(evidence_id: str, details: Dict[str, Any], default_reason: str) -> str:
    template = TEMPLATES.get(evidence_id)
    if not template:
        return default_reason
    try:
        # Provide defaults for common template keys to prevent KeyErrors
        safe_kwargs = {
            "p": details.get("p_ai", details.get("raw_score", 0.0)),
            "score": details.get("score", 0.0),
            "software": details.get("software", "Unknown Editor"),
            "other_id": details.get("other_id", "Prior-Claim"),
            "sim": details.get("similarity", 0.95),
            "expected": details.get("expected", 0.0),
            "found": details.get("found", 0.0),
            "currency": details.get("currency", "INR"),
            "field": details.get("field", "amount"),
            "font_a": details.get("font_a", "CustomFont"),
            "font_b": details.get("font_b", "PrimaryFont"),
            "text": details.get("text", ""),
            "created": details.get("created", ""),
            "modified": details.get("modified", ""),
            "reason": details.get("reason", "Chronological inconsistency"),
            "value": details.get("value", ""),
            "val1": details.get("val1", ""),
            "val2": details.get("val2", ""),
            "words": details.get("words", ""),
            "digits": details.get("digits", 0.0),
            "word": details.get("word", ""),
            "photo_date": details.get("photo_date", ""),
            "incident_date": details.get("incident_date", ""),
            "doc_total": details.get("doc_total", 0.0),
            "claim_total": details.get("claim_total", 0.0),
            "claimant_name": details.get("claimant_name", ""),
            "doc_name": details.get("doc_name", ""),
            "doc_date": details.get("doc_date", ""),
            "claim_date": details.get("claim_date", ""),
            "capture": details.get("capture", ""),
            "modify": details.get("modify", ""),
            "producer": details.get("producer", "PDF Generator"),
        }
        safe_kwargs.update(details)
        return template.format(**safe_kwargs)
    except Exception:
        return default_reason
